### ISSUE TITLE
Resolving Cataphora

### ISSUE THREAD

**Issue by aakashb95** [NeuroSYS-pl/coreference-resolution#1]
Thank you for your solutions with regards to resolving cataphora.
I have a discussion point:
"Bayern Munich stalwart had an excellent outing against Wolfsburg. Robert Lewandowski scored five goals in nine minutes."

resolves as:
"Bayern Munich stalwart had an excellent outing against Wolfsburg. Bayern Munich stalwart  scored five goals in nine minutes."

Expected:
"Robert Lewandowski had an excellent outing against Wolfsburg. Robert Lewandowski scored five goals in nine minutes."

How can we try and resolve this? I am trying to use the longest proper noun mention but above case fails this approach.

**Comment by p-mielniczuk** [comment]
Hi,

First of all thanks for checking out our Github.

Regarding your problem. The solution we provided in this repo is, what we feel, a general improvement over what is available out of the box. Like any other problem, each one requires a different approach. 

That being said, we've checked your case with this given example, and it looks like `spacy` is seeing both "Bayern Munich" as well as "Robert Lewandowski" valid potential candidate mentions for a cluster's head. 

We recommend using `displacy` for visualizing such problems.
![image](https://user-images.githubusercontent.com/66678503/115594296-d8904780-a2d5-11eb-8976-bded3c9f21fd.png)

We can see that "Robert Lewandowski" is considered as PERSON while "Bayern Munich" as ORG. There is no saying which should be or shouldn't be a cluster head.

If you really want the PERS entities being prioritized over ORG ones you can edit the code to accomplish that. However, keep in mind that it might mess with other cases.

The full list of available NERs is as follows:
PERSON:      People, including fictional.
NORP:        Nationalities or religious or political groups.
FAC:         Buildings, airports, highways, bridges, etc.
ORG:         Companies, agencies, institutions, etc.
GPE:         Countries, cities, states.
LOC:         Non-GPE locations, mountain ranges, bodies of water.
PRODUCT:     Objects, vehicles, foods, etc. (Not services.)
EVENT:       Named hurricanes, battles, wars, sports events, etc.
WORK_OF_ART: Titles of books, songs, etc.
LAW:         Named documents made into laws.
LANGUAGE:    Any named language.
DATE:        Absolute or relative dates or periods.
TIME:        Times smaller than a day.
PERCENT:     Percentage, including ”%“.
MONEY:       Monetary values, including unit.
QUANTITY:    Measurements, as of weight or distance.
ORDINAL:     “first”, “second”, etc.
CARDINAL:    Numerals that do not fall under another type. 

Another way to solve this could be to take the candidate mentions for each cluster's head (in the scope of the same cluster, of course) and count how many of their tokens are Named Entities.
In this case, we would have 2/3 for "Bayern Munich stalwart" and 2/2 for "Robert Lewandowski". Then just take the higher number to get a mention which has "the most NERs" in it.

**Comment by aakashb95** [comment]
Thanks for the ideas. I'll try the NER approach. The priority based approach can become very example specific and did not generalize well for me in my examples. I think fine tuning to my dataset could be an option albeit time consuming..

Please correct me if I am wrong, are AllenNLP using spacy NER for coreference resolution? 
I'm under the impression they used spanBERT to identify clusters and made it human readable - and used their resolve function to simply take the first mention and replace it with other mentions in the same cluster. 

Also, i asked [a question](https://github.com/allenai/allennlp/issues/5131) to AllenNLP regarding coreference resolution of large texts which works reasonably well - which surprised me because BERT based models can tokenize maximum 512 tokens right? Thoughts?

**Comment by mmaslankowska-neurosys** [comment]
Yes, we have very similar conclusions regarding the whole problem of coreference resolution! Many approaches seem reasonable but only a few are general enough to provide improvements on various datasets. That's probably also a good idea to fine-tune a model if you have a sufficient number of data samples.

As far as we know, AllenNLP uses `spacy` for tokenization and POS tagging (while CR resolution, not training) only. Their model follows [this paper](https://arxiv.org/pdf/1707.07045.pdf) which states that "*The key idea is to directly **consider all spans** in a document as potential mentions and learn distributions over possible antecedents for each.*" - it suggests that they don't distinct `spacy` NERs in this instance as they consider all found spans equivalently. [Here is a link to a very useful Medium post](https://towardsdatascience.com/deep-into-end-to-end-neural-coreference-model-58c317cfdb83) which reveals more details about the approach implemented by AllenNLP :slightly_smiling_face: 

We were also impressed by the AllenNLP model's ability to work on long text sequences! In comparison with Huggingface Neuralcoref, it seems that the latter works better for short text fragments whereas AllenNLP for longer ones. [The comment below your question](https://github.com/allenai/allennlp/issues/5131#issuecomment-825196521) seems reasonable for this case. A similar approach is implemented in e.g. `huggingface` question answering models - more details you can find [in this tutorial](https://github.com/huggingface/notebooks/blob/master/examples/question_answering.ipynb) :wink:

**Comment by aakashb95** [comment]
Thank you for the links. They've been quite useful.
