### ISSUE TITLE
Coreference Resolution custom training model

### ISSUE THREAD

**Issue by MarurSrikanta** [NeuroSYS-pl/coreference-resolution#3]
Hi NeuroSYS,
Congratulations on the great work with Coreference Resolution model.

Unfortunately, I do not have Ontonotes dataset and am using my .txt file. I am unable to find any useful link to convert .txt file into conll 2012 format. I tried using conll u format for training but did not succeed. It would be great if you can answer the following questions:

1.) Which tool can be used to annotate the text to match the coreferences
2.) Can your packages handle custom training

Looking forward to your response.

Thanks and Regards
Marur Srikanta

**Comment by jamebs** [comment]
Hi Marur!
Thanks for checking out our Github.

Answering your first question, we used the complete datasets and didn't annotate them by ourselves. However, you can check [Prodigy](https://prodi.gy/) (it's a paid solution). The `rel.manual` strategy (https://prodi.gy/docs/recipes#rel-manual) could be especially useful in matching the coreferences.

Regarding custom training, the presented strategies operate on already trained models. But, you can use any model you want by replacing the declaration in `utils.load_models()`. So, I'd recommend checking the AllenNLP and Huggingface's NeuralCoref documentation to perform custom training.
